// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3HJ5XC_a-suwjKMscWRGUptPDY7fnxJI',
    appId: '1:363617900262:android:526d6402b059bd51020d27',
    messagingSenderId: '363617900262',
    projectId: 'money-tracking-se346',
    storageBucket: 'money-tracking-se346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mKqnBJhkOR1rLOnDxEKUdr41BN2Av48',
    appId: '1:363617900262:ios:ac637f255a6848e4020d27',
    messagingSenderId: '363617900262',
    projectId: 'money-tracking-se346',
    storageBucket: 'money-tracking-se346.appspot.com',
    iosBundleId: 'com.example.moneyTracking',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVcTj2WN5ZcDrSXb-hQztCM1EzdEnmLZM',
    appId: '1:363617900262:web:341b1b1c24724382020d27',
    messagingSenderId: '363617900262',
    projectId: 'money-tracking-se346',
    authDomain: 'money-tracking-se346.firebaseapp.com',
    storageBucket: 'money-tracking-se346.appspot.com',
    measurementId: 'G-7M100NZ5F7',
  );

}